dashboards/urls.py
from django.urls import path
from . import views

app_name = 'dashboards'

urlpatterns = [
path('supervisor/', views.supervisor_dashboard, name='supervisor'),
path('admin/', views.admin_dashboard, name='admin'),
path('concierge/', views.concierge_dashboard, name='concierge'),
path('parking_owner/', views.parking_owner_dashboard, name='parking_owner'),
path('resident/', views.resident_dashboard, name='resident'),
path('visit/', views.visit_dashboard, name='visit'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    # URL para la página de inicio usando la vista basada en clase
    path('', views.HomePageView.as_view(), name='index'),
]

pronto_park/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('dashboards/', include('dashboards.urls')),
    path('parkings/', include('parkings.urls')),
    path('residences/', include('residences.urls')),
    path('reservations/', include('reservations.urls')),
    path('alerts/', include('alerts.urls')),
    path('', include('home.urls')),  # Asumiendo que tienes una app 'home' para la página principal
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('', views.reservation_list, name='list'),
    path('create/', views.create_reservation, name='create'),
    path('<int:reservation_id>/', views.reservation_detail, name='detail'),
    path('<int:reservation_id>/cancel/', views.cancel_reservation, name='cancel'),
    path('availability/', views.check_parking_availability, name='availability'),
    path('<int:reservation_id>/approve/', views.approve_reservation, name='approve'),
    path('<int:reservation_id>/reject/', views.reject_reservation, name='reject'),
    path('<int:reservation_id>/approve_visit/', views.approve_visit_reservation, name='approve_visit'),
    path('<int:reservation_id>/reject_visit/', views.reject_visit_reservation, name='reject_visit'),
]

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from users.decorators import role_required
from reservations.models import Reservation, ReservationStatus
from parkings.models import Parking


@login_required
@role_required(["supervisor", "admin", "concierge"])
def concierge_dashboard(request):
    pending_visit_reservations = Reservation.objects.filter(
        status=ReservationStatus.PENDING, parking__visit_parking=True
    )
    return render(
        request,
        "dashboards/concierge_dashboard.html",
        {"pending_visit_reservations": pending_visit_reservations},
    )


@login_required
@role_required(["supervisor", "admin", "parking_owner"])
def parking_owner_dashboard(request):
    pending_reservations = Reservation.objects.filter(
        status=ReservationStatus.PENDING, user=request.user
    )
    return render(
        request,
        "dashboards/parking_owner_dashboard.html",
        {"pending_reservations": pending_reservations},
    )


@login_required
@role_required(["supervisor", "admin", "resident"])
def resident_dashboard(request):
    return render(request, "dashboards/resident_dashboard.html")


@login_required
@role_required(["supervisor"])
def supervisor_dashboard(request):
    pending_visit_reservations = Reservation.objects.filter(
        status=ReservationStatus.PENDING, parking__visit_parking=True
    )
    return render(
        request,
        "dashboards/supervisor_dashboard.html",
        {"pending_visit_reservations": pending_visit_reservations},
    )


@login_required
@role_required(["supervisor", "admin"])
def admin_dashboard(request):
    pending_visit_reservations = Reservation.objects.filter(
        status=ReservationStatus.PENDING, parking__visit_parking=True
    )
    return render(
        request,
        "dashboards/admin_dashboard.html",
        {"pending_visit_reservations": pending_visit_reservations},
    )


def visit_dashboard(request):
    return render(request, "dashboards/visit_dashboard.html")

dashboards/templates/dashboards/admin_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Administrador{% endblock %}

{% block content %}
    <h2>Dashboard Administrador</h2>
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>Reservas Pendientes</h3>
            {% if pending_visit_reservations %}
                {% for reservation in pending_visit_reservations %}
                    <h4>Reserva {{ forloop.counter }}</h4>
                    <ul>
                        <li>Estacionamiento {{ reservation.parking.number }}.</li>
                        <li>Solicitada por {{ reservation.user.first_name }} {{ reservation.user.last_name }}.</li>
                        <li>Desde el {{ reservation.start_datetime }}</li>
                        <li>Hasta el {{ reservation.end_datetime }}</li>
                    </ul>
                    <div class="btn-group d-flex justify-content-evenly">
                        <form method="post"
                              action="{% url 'reservations:approve_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Aprobar</button>
                        </form>
                        <form method="post"
                              action="{% url 'reservations:reject_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Rechazar</button>
                        </form>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <p>No hay reservas pendientes.</p>
            {% endif %}
            <h3>Mis reservas</h3>
        </div>
        <div class="col-12 col-md-8">

            {% include "calendar.html" %}

        </div>
    </div>
{% endblock %}

dashboards/templates/dashboards/concierge_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Conserje{% endblock %}

{% block content %}
    <h2>Dashboard Conserje</h2>
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>Reservas Pendientes</h3>
            {% if pending_visit_reservations %}
                {% for reservation in pending_visit_reservations %}
                    <h4>Reserva {{ forloop.counter }}</h4>
                    <ul>
                        <li>Estacionamiento {{ reservation.parking.number }}.</li>
                        <li>Solicitada por {{ reservation.user.first_name }} {{ reservation.user.last_name }}.</li>
                        <li>Desde el {{ reservation.start_datetime }}</li>
                        <li>Hasta el {{ reservation.end_datetime }}</li>
                    </ul>
                    <div class="btn-group d-flex justify-content-evenly">
                        <form method="post"
                              action="{% url 'reservations:approve_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Aprobar</button>
                        </form>
                        <form method="post"
                              action="{% url 'reservations:reject_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Rechazar</button>
                        </form>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <p>No hay reservas pendientes.</p>
            {% endif %}
            <h3>Mis reservas</h3>
        </div>
        <div class="col-12 col-md-8">

            {% include "calendar.html" %}

        </div>
    </div>
{% endblock %}

dashboards/templates/dashboards/parking_owner_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Propietario{% endblock %}

{% block content %}
    <h2>Dashboard Propietario</h2>
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>Reservas Pendientes</h3>
            {% if pending_reservations %}
                {% for reservation in pending_reservations %}
                    <h4>Reserva {{ forloop.counter }}</h4>
                    <ul>
                        <li>Estacionamiento {{ reservation.parking.number }}.</li>
                        <li>Solicitada por {{ reservation.user.first_name }} {{ reservation.user.last_name }}.</li>
                        <li>Desde el {{ reservation.start_datetime }}</li>
                        <li>Hasta el {{ reservation.end_datetime }}</li>
                    </ul>
                    <div class="btn-group d-flex justify-content-evenly">
                        <form method="post"
                              action="{% url 'reservations:approve' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Aprobar</button>
                        </form>
                        <form method="post" action="{% url 'reservations:reject' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Rechazar</button>
                        </form>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <p>No hay reservas pendientes.</p>
            {% endif %}
            <h3>Mis reservas</h3>
        </div>
        <div class="col-12 col-md-8">

            {% include "calendar.html" %}

        </div>
    </div>
{% endblock %}

dashboards/templates/dashboards/resident_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Residente{% endblock %}

{% block content %}
    <h2>Dashboard Residente</h2>
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>Mis reservas</h3>
        </div>
        <div class="col-12 col-md-8">

            {% include "calendar.html" %}

        </div>
    </div>
{% endblock %}

dashboards/templates/dashboards/supervisor_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Supervisor{% endblock %}

{% block content %}
    <h2>Dashboard Supervisor</h2>
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>Reservas Pendientes</h3>
            {% if pending_visit_reservations %}
                {% for reservation in pending_visit_reservations %}
                    <h4>Reserva {{ forloop.counter }}</h4>
                    <ul>
                        <li>Estacionamiento {{ reservation.parking.number }}.</li>
                        <li>Solicitada por {{ reservation.user.first_name }} {{ reservation.user.last_name }}.</li>
                        <li>Desde el {{ reservation.start_datetime }}</li>
                        <li>Hasta el {{ reservation.end_datetime }}</li>
                    </ul>
                    <div class="btn-group d-flex justify-content-evenly">
                        <form method="post"
                              action="{% url 'reservations:approve_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Aprobar</button>
                        </form>
                        <form method="post"
                              action="{% url 'reservations:reject_visit' reservation.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Rechazar</button>
                        </form>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                <p>No hay reservas pendientes.</p>
            {% endif %}
            <h3>Mis reservas</h3>
        </div>
        <div class="col-12 col-md-8">

            {% include "calendar.html" %}

        </div>
    </div>
{% endblock %}

dashboards/templates/dashboards/visit_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard Visita{% endblock %}

{% block content %}
    <h2>Visit Dashboard Visita</h2>
    <p>Opcional: contenido para visitantes.</p>
    <div class="container row">

        {% include "calendar.html" %}

    </div>
{% endblock %}